version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cisco_script_api
    tty: true
    working_dir: /app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - TZ=Asia/Bangkok
